### ISSUE TITLE
Build failure with gcc-5.3.0 on armhf

### ISSUE THREAD

**Issue by jirutka** [JuliaLang/openlibm#136]
I’ve created an Alpine package for openlibm 0.5.1, it builds fine on x86 and x86_64, but fails on armhf:

```
/home/buildozer/aports/testing/openlibm/src/openlibm-0.5.1/include/openlibm_fenv_arm.h:60:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'extern'
 extern const fenv_t __fe_dfl_env;
 ^
src/s_clog.c:76:1: warning: data definition has no type or storage class
 __strong_alias(clogl, clog);
 ^
src/s_clog.c:76:1: warning: type defaults to 'int' in declaration of '__strong_alias' [-Wimplicit-int]
src/s_clog.c:76:1: warning: parameter names (without types) in function declaration
/home/buildozer/aports/testing/openlibm/src/openlibm-0.5.1/include/openlibm_fenv_arm.h: In function 'feenableexcept':
/home/buildozer/aports/testing/openlibm/src/openlibm-0.5.1/include/openlibm_fenv_arm.h:194:21: warning: variable '__new_fpsr' set but not used [-Wunused-but-set-variable]
  fenv_t __old_fpsr, __new_fpsr;
                     ^
/home/buildozer/aports/testing/openlibm/src/openlibm-0.5.1/include/openlibm_fenv_arm.h: In function 'fedisableexcept':
/home/buildozer/aports/testing/openlibm/src/openlibm-0.5.1/include/openlibm_fenv_arm.h:205:21: warning: variable '__new_fpsr' set but not used [-Wunused-but-set-variable]
  fenv_t __old_fpsr, __new_fpsr;
                     ^
arm/fenv.c: At top level:
arm/fenv.c:40:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'const'
 const fenv_t __fe_dfl_env = 0;
 ^
make: *** [Make.inc:66: arm/fenv.c.o] Error 1
make: *** Waiting for unfinished jobs....
```

You can examine the full log from our build server [here](http://haste.fit.cvut.cz/eletimi.log).

---
OS: Alpine Linux
arch: armhf
compiler: gcc 5.3.0
libc: musl 1.1.14

**Comment by ViralBShah** [comment]
Is this still an issue? I am able to build fine on ubuntu 16.04, which has gcc 5.4.0.

**Comment by ViralBShah** [comment]
Please reopen if necessary.
