### PR TITLE
Revert "Update remaining references to bsd_cdefs.h to cdefs-compat.h."

### LINKED ISSUE #137: libopenlibm.so: undefined reference to `__fpgetprec'
openlibm 0.5.1 fails to pass the tests on Debian unstable i386 (@ginggs, @nalimilan):
```
make -C test test-double
make[1]: Entering directory '/mnt/openlibm/test'
gcc  -O2   test-double.c -D__BSD_VISIBLE -I ../include -I../src -L.. -lopenlibm -Wl,-rpath=/mnt/openlibm -o test-double
../libopenlibm.so: undefined reference to `__fpgetprec'
collect2: error: ld returned 1 exit status
```

A git bisect reveals that this regression was introduced in commit ebcd40f1b0378522b299bfec63e288df000b43d2.

With that commit reverted, openlibm compiles fine on i386.

### PR DESCRIPTION
**Pull request by petercolberg**
This resolves #137.

### CODE REVIEW

**Comment by pao** [comment]
Undoes #134. cc @EdSchouten

**Comment by petercolberg** [comment]
This merge request is superseded by #139.
