### ISSUE TITLE
libopenlibm.so: undefined reference to `__fpgetprec'

### ISSUE THREAD

**Issue by petercolberg** [JuliaLang/openlibm#137]
openlibm 0.5.1 fails to pass the tests on Debian unstable i386 (@ginggs, @nalimilan):
```
make -C test test-double
make[1]: Entering directory '/mnt/openlibm/test'
gcc  -O2   test-double.c -D__BSD_VISIBLE -I ../include -I../src -L.. -lopenlibm -Wl,-rpath=/mnt/openlibm -o test-double
../libopenlibm.so: undefined reference to `__fpgetprec'
collect2: error: ld returned 1 exit status
```

A git bisect reveals that this regression was introduced in commit ebcd40f1b0378522b299bfec63e288df000b43d2.

With that commit reverted, openlibm compiles fine on i386.

**Comment by ginggs** [comment]
The second part of that commit undid https://github.com/JuliaLang/openlibm/pull/103

**Comment by petercolberg** [comment]
As said before on the Debian Julia mailing list, I don’t see why someone would have substituted `cdefs-compat.h` for `bsd_cdefs.h`. The files serve different purposes, in fact they share no common code at all.

It would be super awesome if you could establish a more rigorous review process for merge requests, considering this library is central to Julia and advertised as a high quality replacement for glibc libm.

**Comment by pao** [comment]
cf #134 and 2c3f3b5a9911e79f2d809172e9b2365ef192e3d9, I think?

**Comment by nalimilan** [comment]
Any idea why this failure wasn't caught by the existing test builds, and how to ensure we do test it in the future?

**Comment by EdSchouten** [comment]
Also any idea what's the underlying reason that the original change caused this regression?

**Comment by petercolberg** [comment]
Commit d2eb735a5dc1ebf32a1033e24eafdaf9b4597fe1 of #138 contains an explanation for the regression.

**Comment by petercolberg** [comment]
This failure was not caught because i386 was not tested.

I am working on a proper Travis build matrix for armhf/arm64/i386 in #139.
